"""add some columns

Revision ID: 4a63626152b8
Revises: 05bf3b403fa8
Create Date: 2026-06-18 21:15:29.253313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a63626152b8'
down_revision: Union[str, Sequence[str], None] = '05bf3b403fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('higher_bidder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'user', ['higher_bidder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'higher_bidder_id')
    op.drop_column('item', 'is_active')
    op.drop_column('item', 'end_time')
    # ### end Alembic commands ###
