"""add stripe payment fields

Revision ID: 5ede3fcc1dbc
Revises: 4a63626152b8
Create Date: 2026-06-21 20:51:36.135190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5ede3fcc1dbc'
down_revision: Union[str, Sequence[str], None] = '4a63626152b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('stripe_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('stripe_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_account_id')
    op.drop_column('item', 'stripe_payment_id')
    op.drop_column('item', 'payment_status')
    # ### end Alembic commands ###
