"""add checkout_token

Revision ID: d394b76b2f7e
Revises: 5ede3fcc1dbc
Create Date: 2026-06-22 22:59:09.531532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd394b76b2f7e'
down_revision: Union[str, Sequence[str], None] = '5ede3fcc1dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('checkout_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'checkout_token')
    # ### end Alembic commands ###
